version: "3"

services:
  web:
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
      - REDIS_URL
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine

volumes:
  postgres_data: